{"name": "Проверка принятия заказа с невалидным id курьера", "status": "passed", "start": 1717175439398, "stop": 1717175439586, "uuid": "12a2f043-ebe6-4e67-b094-7c58ad666575", "historyId": "c21411e322ecac6a4aa10c6a8d04c103", "testCaseId": "c21411e322ecac6a4aa10c6a8d04c103", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_with_incorrect_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "lisk"}, {"name": "thread", "value": "6457-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}